[versions]
kotlin = "1.9.21"

[libraries]
mordant = "com.github.ajalt.mordant:mordant:2.2.0"

# used in tests
kotest =  "io.kotest:kotest-assertions-core:5.8.0"
systemrules = "com.github.stefanbirkner:system-rules:1.19.0"
jimfs = "com.google.jimfs:jimfs:1.3.0"

# used in samples
kodein = "org.kodein.di:kodein-di-generic-jvm:6.5.5"
kotlinx-serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.1"

[plugins]
dokka = "org.jetbrains.dokka:1.9.10"
publish = "com.vanniktech.maven.publish:0.25.3"
