[versions]
kotlin = "1.9.23"

[libraries]
mordant = "com.github.ajalt.mordant:mordant:2.5.0"

# used in tests
kotest =  "io.kotest:kotest-assertions-core:5.8.1"
systemrules = "com.github.stefanbirkner:system-rules:1.19.0"
jimfs = "com.google.jimfs:jimfs:1.3.0"

# used in samples
kodein = "org.kodein.di:kodein-di-generic-jvm:6.5.5"
kotlinx-serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.2"

[plugins]
dokka = "org.jetbrains.dokka:1.9.20"
publish = "com.vanniktech.maven.publish:0.28.0"
kotlinBinaryCompatibilityValidator = "org.jetbrains.kotlinx.binary-compatibility-validator:0.14.0"
