[versions]
kotlin = "2.3.0"
coroutines = "1.10.2"
mordant = "3.0.2"

[libraries]
mordant = {module = "com.github.ajalt.mordant:mordant", version.ref = "mordant"}
mordant-markdown = {module = "com.github.ajalt.mordant:mordant-markdown", version.ref = "mordant"}

# used in tests
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotest = "io.kotest:kotest-assertions-core:5.9.1"
systemrules = "com.github.stefanbirkner:system-rules:1.19.0"
jimfs = "com.google.jimfs:jimfs:1.3.1"

# used in samples
kodein = "org.kodein.di:kodein-di-generic-jvm:6.5.5"
kotlinx-serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0"

[plugins]
dokka = "org.jetbrains.dokka:2.1.0"
publish = "com.vanniktech.maven.publish:0.35.0"
kotlinBinaryCompatibilityValidator = "org.jetbrains.kotlinx.binary-compatibility-validator:0.18.1"
